name: locreminder
description: "A location-based alarm app built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Updated dependencies for better stability
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  flutter_local_notifications: ^18.0.1
  vibration: ^2.0.0
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
